// src/components/react/Auth/LoginForm.tsx
'use client';

import React, { FormEvent } from 'react';
import '../../styles/pocketcrud.css';

export interface LoginFormProps {
  email?: string;
  password?: string;
  isLoading?: boolean;
  error?: string;
  title?: string;
  subtitle?: string;
  backLink?: string;
  backText?: string;
  onEmailChange?: (email: string) => void;
  onPasswordChange?: (password: string) => void;
  onSubmit: (data: { email: string; password: string }) => void | Promise<void>;
  emailSlot?: React.ReactNode;
  passwordSlot?: React.ReactNode;
  submitButtonSlot?: React.ReactNode;
  backLinkSlot?: React.ReactNode;
}

export const LoginForm: React.FC<LoginFormProps> = ({
  email = '',
  password = '',
  isLoading = false,
  error = '',
  title = 'Admin Login',
  subtitle = 'Access the collection management interface',
  backLink = '/',
  backText = '← Back to site',
  onEmailChange,
  onPasswordChange,
  onSubmit,
  emailSlot,
  passwordSlot,
  submitButtonSlot,
  backLinkSlot,
}) => {
  const [emailState, setEmailState] = React.useState(email);
  const [passwordState, setPasswordState] = React.useState(password);

  React.useEffect(() => {
    setEmailState(email);
  }, [email]);

  React.useEffect(() => {
    setPasswordState(password);
  }, [password]);

  const handleEmailChange = (e: React.ChangeEvent<HTMLInputElement>) => {
    const value = e.target.value;
    setEmailState(value);
    onEmailChange?.(value);
  };

  const handlePasswordChange = (e: React.ChangeEvent<HTMLInputElement>) => {
    const value = e.target.value;
    setPasswordState(value);
    onPasswordChange?.(value);
  };

  const handleSubmit = async (e: FormEvent<HTMLFormElement>) => {
    e.preventDefault();
    await onSubmit({ email: emailState, password: passwordState });
  };

  return (
    <div className="pocketcrud-login flex min-h-screen items-center justify-center px-4 py-12 sm:px-6 lg:px-8">
      <div className="w-full max-w-md space-y-8">
        <div>
          <h2 className="mt-6 text-center text-3xl font-extrabold">{title}</h2>
          <p className="mt-2 text-center">{subtitle}</p>
        </div>

        <form className="pc-form" onSubmit={handleSubmit}>
          {error && (
            <div className="pocketcrud-alert pocketcrud-alert-error" data-testid="error-message">
              {error}
            </div>
          )}

          <div className="pc-input-group">
            {emailSlot || (
              <input
                id="email"
                name="email"
                type="email"
                autoComplete="email"
                required
                value={emailState}
                onChange={handleEmailChange}
                disabled={isLoading}
                placeholder="Email address"
                className="pocketcrud-input"
                data-testid="email-input"
              />
            )}
            {passwordSlot || (
              <input
                id="password"
                name="password"
                type="password"
                autoComplete="current-password"
                required
                value={passwordState}
                onChange={handlePasswordChange}
                disabled={isLoading}
                placeholder="Password"
                className="pocketcrud-input"
                data-testid="password-input"
              />
            )}
          </div>

          <div>
            {submitButtonSlot || (
              <button
                type="submit"
                disabled={isLoading}
                className="pocketcrud-btn pocketcrud-btn-primary pc-btn-full"
                data-testid="login-button"
              >
                {isLoading ? (
                  <span className="pc-loading">
                    <div className="pocketcrud-spinner"></div>
                    Signing in...
                  </span>
                ) : (
                  'Sign in'
                )}
              </button>
            )}
          </div>

          <div className="pc-links">
            {backLinkSlot || (
              <a href={backLink} className="pc-link">
                {backText}
              </a>
            )}
          </div>
        </form>
      </div>
    </div>
  );
};

export default LoginForm;

// src/components/svelte/Auth/LoginForm.svelte
<script>
  import { createEventDispatcher } from 'svelte';
  import '../../styles/pocketcrud.css';

  /** @type {string} */
  export let email = '';
  /** @type {string} */
  export let password = '';
  /** @type {boolean} */
  export let isLoading = false;
  /** @type {string} */
  export let error = '';
  /** @type {string} */
  export let title = 'Admin Login';
  /** @type {string} */
  export let subtitle = 'Access the collection management interface';
  /** @type {string} */
  export let backLink = '/';
  /** @type {string} */
  export let backText = '← Back to site';

  const dispatch = createEventDispatcher();

  /**
   * @param {Event} e
   */
  async function handleSubmit(e) {
    e.preventDefault();
    dispatch('submit', { email, password });
  }
</script>

<div
  class="pocketcrud-login flex min-h-screen items-center justify-center px-4 py-12 sm:px-6 lg:px-8"
>
  <div class="w-full max-w-md space-y-8">
    <div>
      <h2 class="mt-6 text-center text-3xl font-extrabold">{title}</h2>
      <p class="mt-2 text-center">{subtitle}</p>
    </div>

    <form class="pc-form" on:submit={handleSubmit}>
      {#if error}
        <div class="pocketcrud-alert pocketcrud-alert-error" data-testid="error-message">
          {error}
        </div>
      {/if}

      <div class="pc-input-group">
        <slot name="email-input">
          <input
            id="email"
            name="email"
            type="email"
            autocomplete="email"
            required
            bind:value={email}
            disabled={isLoading}
            placeholder="Email address"
            class="pocketcrud-input"
            data-testid="email-input"
          />
        </slot>
        <slot name="password-input">
          <input
            id="password"
            name="password"
            type="password"
            autocomplete="current-password"
            required
            bind:value={password}
            disabled={isLoading}
            placeholder="Password"
            class="pocketcrud-input"
            data-testid="password-input"
          />
        </slot>
      </div>

      <div>
        <slot name="submit-button">
          <button
            type="submit"
            disabled={isLoading}
            class="pocketcrud-btn pocketcrud-btn-primary pc-btn-full"
            data-testid="login-button"
          >
            {#if isLoading}
              <span class="pc-loading">
                <div class="pocketcrud-spinner"></div>
                Signing in...
              </span>
            {:else}
              Sign in
            {/if}
          </button>
        </slot>
      </div>

      <div class="pc-links">
        <slot name="back-link">
          <a href={backLink} class="pc-link">{backText}</a>
        </slot>
      </div>
    </form>
  </div>
</div>

<style>
  .pc-form {
    margin-top: var(--pc-spacing-xl);
    display: flex;
    flex-direction: column;
    gap: var(--pc-spacing-lg);
  }

  .pc-input-group {
    display: flex;
    flex-direction: column;
    gap: var(--pc-spacing-md);
    width: 100%;
  }

  .pc-btn-full {
    width: 100%;
    justify-content: center;
  }

  .pc-loading {
    display: flex;
    align-items: center;
    gap: var(--pc-spacing-sm);
  }

  .pc-links {
    display: flex;
    flex-direction: column;
    gap: var(--pc-spacing-sm);
    text-align: center;
  }

  .pc-link {
    font-size: var(--pc-font-size-sm);
    color: var(--pc-primary);
    text-decoration: none;
    transition: color var(--pc-transition-speed) var(--pc-transition-timing);
  }

  .pc-link:hover {
    color: var(--pc-primary-hover);
  }
</style>
